# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.places.importBookmarksHTML", true);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.smartBookmarksVersion", 0);
user_pref("dom.disable_window_open_feature.status", false);
user_pref("intl.accept_languages", "en-us,en");
user_pref("intl.charset.default", "UTF-8");
user_pref("javascript.enabled", true);
