# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1248026681);
user_pref("app.update.lastUpdateTime.background-update-timer", 1248026680);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1248026680);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1248026681);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1254423466);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1248026683);
user_pref("browser.bookmarks.editDialog.firstEditField", "namePicker");
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://www.caelum.com.br/home/SP/FJ-27");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.2.13");
user_pref("browser.tabs.forceHide", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "firebug@software.joehewitt.com:1.6.0,yslow@yahoo-inc.com:2.1.0,langpack-en-GB@firefox-3.6.ubuntu.com:3.6,ubufox@ubuntu.com:0.9rc2,{c45c406e-ab73-11d8-be73-000a95be3b12}:1.1.8,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.13");
user_pref("extensions.firebug.currentVersion", "1.6.0");
user_pref("extensions.lastAppVersion", "3.6.13");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", true);
user_pref("privacy.cpd.downloads", true);
user_pref("privacy.cpd.formdata", true);
user_pref("privacy.cpd.history", true);
user_pref("privacy.cpd.sessions", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1296151674);
user_pref("webdeveloper.custom.1.color", "#ff0000");
user_pref("webdeveloper.custom.2.color", "#33ff33");
user_pref("webdeveloper.custom.3.color", "#3333ff");
user_pref("webdeveloper.custom.4.color", "#ff0000");
user_pref("webdeveloper.custom.5.color", "#33ff33");
user_pref("webdeveloper.dashboard.position", "bottom");
user_pref("webdeveloper.disable.styles.key", "S");
user_pref("webdeveloper.display.element.information.key", "F");
user_pref("webdeveloper.edit.color.background", "#ffffff");
user_pref("webdeveloper.edit.color.text", "#000000");
user_pref("webdeveloper.edit.css.key", "E");
user_pref("webdeveloper.edit.font.size", 12);
user_pref("webdeveloper.edit.update.frequency", 2000);
user_pref("webdeveloper.error.console.key", "J");
user_pref("webdeveloper.feature.tooltip.color.background", "#ffff99");
user_pref("webdeveloper.feature.tooltip.color.border", "#ffcc66");
user_pref("webdeveloper.feature.tooltip.color.text", "#000000");
user_pref("webdeveloper.feature.tooltip.opacity", "0.9");
user_pref("webdeveloper.generated.content.font.size", 12);
user_pref("webdeveloper.information.tidy", true);
user_pref("webdeveloper.java.console.key", "O");
user_pref("webdeveloper.line.guides.color", "#000000");
user_pref("webdeveloper.magnification.level", "2");
user_pref("webdeveloper.open.tabs", true);
user_pref("webdeveloper.populate.form.fields.email", "example@example.com");
user_pref("webdeveloper.resize.1.description", "800x600");
user_pref("webdeveloper.resize.1.height", 600);
user_pref("webdeveloper.resize.1.width", 800);
user_pref("webdeveloper.resize.count", 1);
user_pref("webdeveloper.style.information.dashboard", true);
user_pref("webdeveloper.tool.1.description", "Validate CSS");
user_pref("webdeveloper.tool.1.url", "http://jigsaw.w3.org/css-validator/validator?profile=css21&warning=0&uri=");
user_pref("webdeveloper.tool.2.description", "Validate Feed");
user_pref("webdeveloper.tool.2.url", "http://validator.w3.org/feed/check.cgi?url=");
user_pref("webdeveloper.tool.3.description", "Validate HTML");
user_pref("webdeveloper.tool.3.key", "H");
user_pref("webdeveloper.tool.3.url", "http://validator.w3.org/check?verbose=1&uri=");
user_pref("webdeveloper.tool.4.description", "Validate Links");
user_pref("webdeveloper.tool.4.url", "http://validator.w3.org/checklink?check=Check&hide_type=all&summary=on&uri=");
user_pref("webdeveloper.tool.5.description", "Validate Section 508");
user_pref("webdeveloper.tool.5.url", "http://www.cynthiasays.com/mynewtester/cynthia.exe?rptmode=-1&url1=");
user_pref("webdeveloper.tool.6.description", "Validate WAI");
user_pref("webdeveloper.tool.6.url", "http://www.cynthiasays.com/mynewtester/cynthia.exe?rptmode=2&url1=");
user_pref("webdeveloper.tool.count", 6);
user_pref("webdeveloper.toolbar.key", "B");
user_pref("webdeveloper.validate.local.accessibility.section508", true);
user_pref("webdeveloper.validate.local.accessibility.wai.priority1", true);
user_pref("webdeveloper.validate.local.css.profile", "css21");
user_pref("webdeveloper.validate.local.html.key", "A");
user_pref("webdeveloper.version", "1.18");
user_pref("webdeveloper.view.css.key", "C");
user_pref("webdeveloper.view.source.key", "U");
user_pref("webdeveloper.view.style.information.key", "Y");
user_pref("webdeveloper.zoom.in.key", "Z");
user_pref("webdeveloper.zoom.out.key", "X");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
user_pref("xpinstall.whitelist.add.36", "");
user_pref("xxx.legal.rights.seen", "0.0");
